name: Ansible Provision

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  ansible:
    name: Configure EC2 with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update branch
        uses: actions/checkout@v3
        with:
          ref: update-ec2-ip
          fetch-depth: 1

      - name: Read EC2 public IP from file
        id: read_ip
        run: |
          IP=$(cat terraform/ec2_ip.txt)
          echo "EC2_IP=$IP" >> $GITHUB_ENV
          echo "Read IP: $IP"

      - name: Create private key file
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > cicd.pem
          chmod 600 cicd.pem

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          IP: ${{ env.EC2_IP }}
        run: |
          echo "Using IP: $IP"
          ansible-playbook ansible/playbook.yml \
            -i "$IP," \
            --private-key cicd.pem \
            -u ec2-user