name: Ansible Provision

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  ansible:
    name: Configure EC2 with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update branch
        uses: actions/checkout@v3
        with:
          ref: update-ec2-ip
          fetch-depth: 1

      - name: Read EC2 public IP from file
        id: read_ip
        run: |
          IP=$(cat terraform/ec2_ip.txt | head -n 1 | tr -d '\r\n')
          echo "ec2_ip=$IP" >> "$GITHUB_OUTPUT"
          echo "Read IP: $IP"

      - name: Debug - Show IP
        run: echo "EC2 IP: ${{ steps.read_ip.outputs.ec2_ip }}"

      - name: Create private key file
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > cicd.pem
          chmod 600 cicd.pem

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml \
            -i "${{ steps.read_ip.outputs.ec2_ip }}," \
            --private-key cicd.pem \
            -u ec2-user