name: Ansible Provision

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  ansible:
    name: Configure EC2 with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update branch
        uses: actions/checkout@v3
        with:
          ref: update-ec2-ip
          fetch-depth: 1

      - name: Read EC2 public IP from file
        id: read_ip
        run: |
          IP=$(head -n 1 terraform/ec2_ip.txt | tr -d '\r\n')
          echo "EC2_IP=$IP" >> $GITHUB_ENV
          echo "Read IP: $IP"

      - name: Debug EC2 IP
        run: echo "EC2 IP is '${{ env.EC2_IP }}'"

      - name: Create private key file
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > cicd.pem
          chmod 600 cicd.pem

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml \
            -i "${{ env.EC2_IP }}," \
            --private-key cicd.pem \
            -u ec2-user